name: argon2_ffi_base
description: Base package defining the interface for an Argon2 implementation.
version: 0.1.4+1
homepage: https://github.com/authpass/argon2_ffi_base

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  logging: ^0.11.4

dev_dependencies:
  pedantic: ^1.9.2
