name: argon2_ffi_base
description: Base package defining the interface for an Argon2 implementation.
version: 0.1.1
homepage: https://github.com/authpass/argon2_ffi_base

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  ffi_helper: ^1.4.0

dev_dependencies:
  pedantic: ^1.9.0
